name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up uv
      uses: astral-sh/setup-uv@v1
      with:
        version: "latest"

    - name: Build package
      run: uv build

    - name: Publish to PyPI
      run: uv publish 