name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up uv
      uses: astral-sh/setup-uv@v1
      with:
        version: "latest"

    - name: Publish to PyPI
      run: uv build

    - name: Publish to PyPI
      run: uv publish 